services:

  cache:
    image: redis
    restart: no
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - ./docker-compose/redis:/data
    networks:
      - minecraft
